version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: techmarket_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: techmarketpro
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - techmarket-network

  techmarket-app:
    build: .
    container_name: techmarket_app
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      APP_DATABASE_TYPE: mongodb
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/techmarketpro?authSource=admin
    depends_on:
      - mongodb
    networks:
      - techmarket-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    container_name: techmarket_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - techmarket-app
    networks:
      - techmarket-network

volumes:
  mongodb_data:
    driver: local

networks:
  techmarket-network:
    driver: bridge